
server:
  port: 8888
  servlet-path: /springboot
spring:
  profiles: zn
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot
    username: root
    password: 123456
#常量区域
name: name-hello
hello: hello-world

content: "name: ${name},hello: ${hello}"

student:
  name: 中国
  age: 20